#!/bin/python3

'''
Literals by default of the SUBCLASSES
'''

# MessageOrigin
DEFAULT_MESSAGE_ORIGIN_USER = 'user'
DEFAULT_MESSAGE_ORIGIN_HIDDEN_USER = 'hidden_user'
DEFAULT_MESSAGE_ORIGIN_CHAT = 'chat'
DEFAULT_MESSAGE_ORIGIN_CHANNEL = 'channel'

# ChatBoostSource
DEFAULT_CHAT_BOOST_SOURCE_PREMIUM = 'premium'
DEFAULT_CHAT_BOOST_SOURCE_GIFT_CODE = 'gift_code'
DEFAULT_CHAT_BOOST_SOURCE_GIVEAWAY = 'giveaway'

# ReactionType
DEFAULT_REACTION_TYPE_EMOJI = 'emoji'
DEFAULT_REACTION_TYPE_CUSTOM_EMOJI = 'custom_emoji'

# ChatMember
DEFAULT_CHAT_MEMBER_OWNER = 'creator'
DEFAULT_CHAT_MEMBER_ADMINISTRATOR = 'administrator'
DEFAULT_CHAT_MEMBER_MEMBER = 'member'
DEFAULT_CHAT_MEMBER_RESTRICTED = 'restricted'
DEFAULT_CHAT_MEMBER_LEFT = 'left'
DEFAULT_CHAT_MEMBER_BANNED = 'kicked'

# BotCommandScope
DEFAULT_BOT_COMMAND_SCOPE_DEFAULT = 'default'
DEFAULT_BOT_COMMAND_SCOPE_ALL_PRIVATE_CHATS = 'all_private_chats'
DEFAULT_BOT_COMMAND_SCOPE_ALL_GROUP_CHATS = 'all_group_chats'
DEFAULT_BOT_COMMAND_SCOPE_ALL_CHAT_ADMINISTRATORS = 'all_chat_administrators'
DEFAULT_BOT_COMMAND_SCOPE_CHAT = 'chat'
DEFAULT_BOT_COMMAND_SCOPE_CHAT_ADMINISTRATORS = 'chat_administrators'
DEFAULT_BOT_COMMAND_SCOPE_CHAT_MEMBER = 'chat_member'
